### ISSUE TITLE
Original image URLs via Tachyon timeout

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-media#34]
Currently we pass the original image URL to tachyon too, such as https://platform-test.aws.hmn.md/tachyon/2019/08/robert-lukeman-_RBcxo9AU-U-unsplash.jpg. This _might_ be intentional, but the original I think is better staying the original, as they can be very large and we have problems with large images in Tachyon.

**Comment by roborourke** [comment]
I think we could deal with this in a few places. Some ideas:

- force a maximum size even when requesting a full size image
  - could be done in tachyon itself
  - could be done in tachyon plugin or media module
  - could add a query param flag to make the full size request intentional
- pass through / redirect to original URL and do no processing when requesting full size

- smart media, needs to know original dimensions but can display a smaller version in the UI
  - cropping calculations become a bit trickier but would perform better

**Comment by roborourke** [comment]
The reason behind this is that the cropping relies on CORS headers being set or the image coming from the same origin. I _think_ this is only an issue on local server but would come up for anything where we still have the legacy tachyon URLs.

**Comment by roborourke** [comment]
Additional reasons for using tachyon even for original image URLs is webp & other optimisations from sharp.

Maybe the solution is to set a maximum size that can be returned from tachyon even when requesting the original.

**Comment by roborourke** [comment]
Update: large image handling is shipping in WP 5.3, likely this weekend at WCUS.

In addition we're increasing the tachyon memory limits to help with processing large buffers.

**Comment by roborourke** [comment]
Given the changes to Tachyon and our deployment we could close this one out.

**Comment by roborourke** [comment]
No more reports since updating the service to 1Gb ram, and WP 5.3 rolled out
